/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellAskRouteImport } from './routes/_shell.ask'
import { Route as ShellMattersRouteImport } from './routes/_shell.matters'
import { Route as ShellVaultRouteImport } from './routes/_shell.vault'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAskRoute = ShellAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMattersRoute = ShellMattersRouteImport.update({
  id: '/matters',
  path: '/matters',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVaultRoute = ShellVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/ask': typeof ShellAskRoute
  '/matters': typeof ShellMattersRoute
  '/vault': typeof ShellVaultRoute
}
export interface FileRoutesByTo {
  '/ask': typeof ShellAskRoute
  '/matters': typeof ShellMattersRoute
  '/vault': typeof ShellVaultRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/ask': typeof ShellAskRoute
  '/_shell/matters': typeof ShellMattersRoute
  '/_shell/vault': typeof ShellVaultRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ask' | '/matters' | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to: '/ask' | '/matters' | '/vault' | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/ask'
    | '/_shell/matters'
    | '/_shell/vault'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ask': {
      id: '/_shell/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof ShellAskRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/matters': {
      id: '/_shell/matters'
      path: '/matters'
      fullPath: '/matters'
      preLoaderRoute: typeof ShellMattersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/vault': {
      id: '/_shell/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof ShellVaultRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAskRoute: typeof ShellAskRoute
  ShellMattersRoute: typeof ShellMattersRoute
  ShellVaultRoute: typeof ShellVaultRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAskRoute: ShellAskRoute,
  ShellMattersRoute: ShellMattersRoute,
  ShellVaultRoute: ShellVaultRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
